FROM python:3.8.10
WORKDIR /dj_crud_stocks
COPY /dj_crud_stocks /src
RUN pip install --no-cache-dir --upgrade -r /src/requirements.txt
ENV SECRET_KEY django-insecure-nw^y+m^wmxza1asgk+)!ua2qx9)g+#v=6%76-9i8i(6eqiw94j
WORKDIR /src
