version: "3.9"

volumes:
  pgdata:

services:
  postgredb:
    image: postgres:latest
    environment:
      POSTGRES_DB: "netology_stocks_products"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "111"
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./logs:/var/log

  backend:
    build: .
    depends_on:
      - postgredb
    entrypoint: ./entrypoint.sh
    volumes:
      - ./dj_crud_stocks/:/usr/src/dj_crud_stocks/
      - ./static:/usr/src/dj_crud_stocks/static/
    expose:
      - 8000

  nginx:
    build: ./nginx
    depends_on:
      - backend
    ports:
      - "1337:80"


